#!/bin/sh

export LC_ALL=C
export TZ="UTC 0"

#set -e
cwd=$(pwd)
base=$(dirname $0)
srcroot="${cwd}/${base}/.."

DCT_THEATER="Caucasus_dctdemo"
DCT_SRC_ROOT="${srcroot}"
DCT_DATA_ROOT="${DCT_DATA_ROOT:-${srcroot}/data}"
export DCT_DATA_ROOT
export DCT_SRC_ROOT
export DCT_THEATER
#echo "lua-path: ${LUA_PATH}"
#echo "DCT data root: ${DCT_DATA_ROOT}"

cd "${base}"
busted $@
rc=$?
cd "${cwd}"
exit $rc
